###
# Project or Lab name
###

name:           "Center for Spatial and Textual Analysis"
sub-name:       "CESTA"
homepage_image:
type:           lab # is this a `lab` site or `project` site?

###
# Options
###

markdown:     redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks","autolink","tables"]
highlighter:  rouge
description:  "The Center for Spatial and Textual Analysis (CESTA) is comprised of the Spatial History Project, Humanities+Design, and the Literary Lab, the Poetic Media Lab, as well as Text Technologies and Chinese Railroad Workers. This interdisciplinary collective of labs operates independently of any one particular home department, and is organizationally housed within the Dean of Research at Stanford University."
destination:  'built'
url:          ''
baseurl:      ''
permalink:    pretty
twitter:      'CESTA_Stanford'
facebook:     'cesta.stanford'

###
# Images
###

#This is the base directory (cloud) where we share images
img-url:           "https://googledrive.com/host/0B_L3W8DD67iAVUktdHIxN0RnUjA/"
banner-img-url:    "https://googledrive.com/host/0B_L3W8DD67iAVUktdHIxN0RnUjA/"

###
# Navigation
###
nav:
  - title: Home
    url: /
  - title: "About"
    url: /about/
  - title: "People"
    url: /people/
  - title: "Labs"
    url: /labs/
    subcategories:
      - subtitle: "Humanities+Design"
        suburl: "http://hdlab.stanford.edu"
      - subtitle: "Spatial History Project"
        suburl: "http://spatialhistory.stanford.edu"
      - subtitle: "Literary Lab"
        suburl: "http://litlab.stanford.edu"
      - subtitle: "Poetic Media"
        suburl: "https://poeticmedia.stanford.edu/" 
  - title: "Projects"
    url: /projects/
    subcategories:
      - subtitle: "Chinese Railroad Workers"
        suburl: "http://web.stanford.edu/group/chineserailroad/cgi-bin/wordpress/"
      - subtitle: "Text/Technologies"
        suburl: "https://texttechnologies.stanford.edu/"
      - subtitle: "Grand Tour"
        suburl: "http://grandtour.stanford.edu/"
  - title: "Graduate Programs"
    url: /graduate/
    subcategories:
      - subtitle: "Graduate Certificate of Digital Humanities"
        suburl:   /graduate/gcdh/
      - subtitle: "Digital History Reading Group"
        suburl:   /graduate/dh-reading/
      - subtitle: "Digital Humanities Graduate Fellows"
        suburl:   /graduate/dh-fellows/
  - title: "Undergraduate Programs"
    url: /undergraduate/
    subcategories:
      - subtitle: "Digital Humanities Undergraduate Minor"
        suburl:   /undergraduate/dh-minor/
      - subtitle: "Research Assistantships"
        suburl: /undergraduate/assistantships/
  - title: "Affiliates"
    url: /affiliates/
    subcategories:
      - subtitle: "Stanford Humanities Center"
        suburl: "http://shc.stanford.edu"
      - subtitle: "DH@Stanford"
        suburl: "http://digitalhumanities.stanford.edu"

###
# Exclude
###

exclude: [vendor]
